local child = coroutine.create(function(a)
  local function nested()
    local x, y, z = coroutine.yield("waiting", a, nil)
    return x, y, z
  end
  return nested()
end)
assert(coroutine.status(child) == "suspended")
local first = table.pack(coroutine.resume(child, 10))
assert(first.n == 4 and first[1] == true and first[2] == "waiting" and first[3] == 10 and first[4] == nil)
local second = table.pack(coroutine.resume(child, 17, nil, 3))
assert(second.n == 4 and second[1] == true and second[2] == 17 and second[3] == nil and second[4] == 3)
assert(coroutine.status(child) == "dead")
assert(coroutine.resume(child) == false)
local outer
outer = coroutine.create(function()
  local inner = coroutine.create(function()
    assert(coroutine.status(outer) == "normal")
    return coroutine.yield("inner")
  end)
  assert(coroutine.resume(inner))
  coroutine.yield("outer")
  return coroutine.resume(inner, 42)
end)
assert(select(2, coroutine.resume(outer)) == "outer")
local result = table.pack(coroutine.resume(outer))
assert(result.n == 3 and result[1] and result[2] and result[3] == 42)
local marker = {}
local ok, err = pcall(function() error(marker) end)
assert(not ok and err == marker)
local ok2, transformed = xpcall(function() error("bad") end, function(err) return "handled:" .. err end)
assert(not ok2 and transformed == "handled:bad")
local protected = coroutine.create(function()
  return pcall(function()
    local value = coroutine.yield("protected")
    return value, nil, 5
  end)
end)
assert(select(2, coroutine.resume(protected)) == "protected")
local final = table.pack(coroutine.resume(protected, 9))
assert(final.n == 5 and final[1] and final[2] and final[3] == 9 and final[4] == nil and final[5] == 5)
local failed = coroutine.create(function() error("failed") end)
local failure = table.pack(coroutine.resume(failed))
assert(failure.n == 2 and failure[1] == false and failure[2] == "failed")
assert(coroutine.status(failed) == "dead")
assert(pcall(17) == false)
local native = coroutine.create(type)
local native_result = table.pack(coroutine.resume(native, true))
assert(native_result.n == 2 and native_result[1] and native_result[2] == "boolean")
local native_failed = coroutine.create(error)
local native_failure = table.pack(coroutine.resume(native_failed, marker))
assert(native_failure.n == 2 and native_failure[1] == false and native_failure[2] == marker)
assert(coroutine.status(native_failed) == 'dead')
local protected_native = coroutine.create(error)
local protected_native_failure = table.pack(pcall(coroutine.resume, protected_native, 'child-error'))
assert(protected_native_failure.n == 3 and protected_native_failure[1] == true
  and protected_native_failure[2] == false and protected_native_failure[3] == 'child-error')
assert(coroutine.status(protected_native) == 'dead')
local native_yield = coroutine.create(coroutine.yield)
local native_yielded = table.pack(coroutine.resume(native_yield, 7, nil))
assert(native_yielded.n == 3 and native_yielded[1] and native_yielded[2] == 7 and native_yielded[3] == nil)
local native_resumed = table.pack(coroutine.resume(native_yield, 9, nil))
assert(native_resumed.n == 3 and native_resumed[1] and native_resumed[2] == 9 and native_resumed[3] == nil)
assert(coroutine.status(native_yield) == 'dead')
local nil_error = table.pack(pcall(error, nil))
assert(nil_error.n == 2 and nil_error[1] == false and nil_error[2] == nil)
local false_error = table.pack(pcall(error, false))
assert(false_error.n == 2 and false_error[1] == false and false_error[2] == false)
local handler_failure = table.pack(xpcall(function() error("bad") end, function() error("again") end))
assert(handler_failure.n == 2 and not handler_failure[1] and handler_failure[2] == "error in error handling")
return "coroutines-pass"
