assert(fs.isDir("/") and fs.isDir("/rc") and fs.isReadOnly("/rc/apis/colors.lua"))
assert(not fs.exists("/mnt/peer/local.lua") and not fs.exists("/etc/passwd"))
assert(fs.open("/rc/apis/colors.lua", "w") == nil)
assert(not pcall(fs.delete, "/rc"))
assert(not pcall(fs.makeDir, "/rc/new"))
assert(not pcall(fs.move, "/rc/apis/colors.lua", "/stolen.lua"))
local rom = assert(fs.open("/rc/apis/colors.lua", "r"))
local source = rom.readAll()
assert(type(source) == "string" and #source > 100)
rom.close()
assert(not pcall(rom.readAll))
fs.makeDir("/work/nested")
assert(fs.isDir("/work/nested"))
local out = assert(io.open("/work/nested/data.txt", "w+"))
assert(io.type(out) == "file")
out:write("alpha\nbeta\n")
assert(out:seek("set", 0) == 0 and out:read(5) == "alpha")
assert(out:read(1) == "\n" and out:read("l") == "beta")
assert(out:read("l") == nil)
out:seek("set", 0)
for i = 1, 2000 do local discard = {i} end
assert(out:read("L") == "alpha\n")
assert(not pcall(out.seek, out, "set", -1))
out:close()
assert(io.type(out) == "closed file" and not pcall(out.write, out, "bad"))
local count, all = 0, ""
for line in io.lines("/work/nested/data.txt") do count = count + 1; all = all .. line end
assert(count == 2 and all == "alphabeta")
fs.copy("/work", "/copied")
fs.move("/copied/nested/data.txt", "/copied/moved.txt")
assert(fs.exists("/copied/moved.txt") and not fs.exists("/copied/nested/data.txt"))
assert(fs.getSize("/copied/moved.txt") == 11)
local append = assert(fs.open("/copied/moved.txt", "a"))
append.writeLine("tail")
append.close()
local reader = assert(fs.open("/copied/moved.txt", "r"))
assert(reader.readAll() == "alpha\nbeta\ntail\n")
reader.close()
local names = fs.list("/copied")
assert(#names == 2 and names[1] == "moved.txt" and names[2] == "nested")
assert(fs.combine("work", "nested", "../test") == "work/test")
assert(fs.getName("/copied/moved.txt") == "moved.txt" and fs.getDir("/copied/moved.txt") == "copied")
assert(fs.getName("") == "" and fs.getDir("") == "", "empty completion prefix has empty metadata")
assert(fs.open("", "w") == nil, "empty file path cannot overwrite root")
fs.makeDir("") -- Existing root-directory no-op remains compatible.
assert(fs.isDir("/") and fs.exists("/copied/moved.txt"))
assert(not pcall(fs.getName, "bad\0path") and not pcall(fs.getDir, "bad\0path"))
fs.copy("/rc/apis/colors.lua", "/colors.lua")
assert(assert(fs.open("/colors.lua", "r")).readAll() == source)
fs.delete("/work")
assert(not fs.exists("/work"))
assert(io.open("/bad\0file", "w") == nil)
assert(io.open("/invalid-mode", "br") == nil)
local bytes = assert(fs.open("/bytes", "wb"))
bytes.write(0)
bytes.write(255)
bytes.write("Z")
assert(not pcall(bytes.write, -1))
bytes.close()
bytes = assert(fs.open("/bytes", "rb"))
assert(bytes.read() == 0 and bytes.read(1) == string.char(255) and bytes.read() == 90 and bytes.read() == nil)
bytes.close()
return "filesystem-pass"
