local s = 'abc123abc'
local first, last, letters, digits = string.find(s, '(%a+)(%d+)%1')
assert(first == 1 and last == #s and letters == 'abc' and digits == '123')
assert(string.match('a123b456b', 'a(.*)b') == '123b456')
assert(string.match('a123b456b', 'a(.-)b') == '123')
assert(string.match('42 word!', '%f[%a]%a+') == 'word')
assert(string.match('x(a(b)c)y', '%b()') == '(a(b)c)')
assert(string.match('aa', '%baa') == 'aa')
assert(string.match(']]', '[]]+') == ']]')
assert(string.match('ab-12', '[a-z]+%-[0-9]+') == 'ab-12')
assert(string.match('\0', '%z') == '\0')
assert(string.match('A', '%l') == nil and string.match('A', '%L') == 'A')
assert(string.match('abc', '^bc') == nil and string.match('abc', '^bc', 2) == 'bc')
assert(string.find('a.b', '.', 1, true) == 2)
assert(string.find('abc', '', #s + 10) == nil)
local left, right = string.match('xy', '()xy()')
assert(left == 1 and right == #'xy' + 1)
local items = {}
for item in string.gmatch('/rc/a//b', '[^/]+') do table.insert(items, item) end
assert(table.concat(items, ',') == 'rc,a,b')
local iter = string.gmatch('ab', '')
assert(iter() == '' and iter() == '' and iter() == '' and iter() == nil)
assert(string.gmatch('abc', '^a')() == nil)
local result, count = string.gsub('a.b.c', '%.', '/')
assert(result == 'a/b/c' and count == 2)
assert(string.gsub('x=one y=two', '(%w+)=(%w+)', '%2:%1') == 'one:x two:y')
assert(string.gsub('abc', '', '-') == '-a-b-c-')
assert(string.gsub('abc', 'a*', '-') == '--b-c-')
assert(string.gsub('cat dog', '%w+', {cat='leaf'}) == 'leaf dog')
assert(string.gsub('ab', '.', function(value) return value:upper() end) == 'AB')
assert(string.gsub('aaa', 'a', 'b', 2) == 'bba')
local unchanged, changed = string.gsub('ab', '.', function() return false end)
assert(unchanged == 'ab' and changed == 2)
assert(not pcall(string.gsub, 'a', '.', function() return true end))
assert(not pcall(string.gsub, 'aa', '.', function() return string.rep('x', 40000) end))
assert(not pcall(string.gsub, 'aaa', 'a', false))
assert(not pcall(string.match, 'a', '['))
assert(not pcall(string.match, 'a', '%'))
assert(not pcall(string.match, 'a', '%1'))
local replacing = coroutine.create(function()
  return string.gsub('ab', '.', function(value) coroutine.yield(value); return value:upper() end)
end)
assert(select(2, coroutine.resume(replacing)) == 'a')
assert(select(2, coroutine.resume(replacing)) == 'b')
local ok, replaced, replacements = coroutine.resume(replacing)
assert(ok and replaced == 'AB' and replacements == 2)
local owner = {kind = 'closure', proto = {leaf = 7}}
for i = 1, 2000 do local discarded = {i} end
assert(owner.proto.leaf == 7, 'guest data named proto must remain a collector root')
return 'patterns-pass'
