assert(game == nil and storage == nil and script == nil and remote == nil and defines == nil)
assert(type(io) == "table" and io.popen == nil and io.tmpfile == nil and io.input == nil)
assert(package == nil and require == nil)
assert(type(os) == "table" and os.execute == nil and os.getenv == nil and os.remove == nil)
assert(loadstring == nil and getfenv == nil and setfenv == nil)
assert(string.dump == nil and debug.getinfo == nil and debug.getregistry == nil and debug.sethook == nil)
local source = assert(load("return 12, nil, 3", "source", "t"))
assert(type(source) == "function")
local result = table.pack(source())
assert(result.n == 3 and result[1] == 12 and result[2] == nil and result[3] == 3)
local env = {value = 41}
local isolated = assert(load("value = value + 1; return value, game, _G", "isolated", "t", env))
local v, host, globals = isolated()
assert(v == 42 and env.value == 42 and host == nil and globals == nil)
assert(value == nil)
assert(load("return 1", "binary-mode", "b") == nil)
assert(load(string.char(27) .. "Lua", "binary") == nil)
assert(load("local =", "syntax") == nil)
assert(load(function() return "return 1" end) == nil)
assert(loadfile("/mnt/peer/local.lua") == nil)
assert(loadfile("/../../etc/passwd") == nil)
assert(loadfile("/local.lua" .. string.char(0)) == nil)
local local_result = table.pack(assert(loadfile("/local.lua"))())
assert(local_result.n == 3 and local_result[1] == "local-pass" and local_result[2] == nil and local_result[3] == 7)
assert(dofile("/local.lua") == "local-pass")
local escaped = assert(load("return game, storage, io.popen, os.execute, remote, package, require"))
local attempt = table.pack(escaped())
assert(attempt.n == 7)
for i = 1, attempt.n do assert(attempt[i] == nil) end
local native = string.sub
assert(type(native) == "function" and not pcall(function() return native.name end))
assert(getmetatable("text").__index == string)
assert(string.sub("abc", 2) == "bc" and ("abc"):upper() == "ABC")
assert(string.rep("x", 3, ":") == "x:x:x" and string.reverse("abc") == "cba")
assert(string.char(65, 66) == "AB" and string.byte("ABC", 2) == 66)
assert(table.concat({"a", 2, "c"}, ":") == "a:2:c")
assert(math.floor(1.9) == 1 and math.max(3, 2, 1) == 3 and bit32.band(7, 3) == 3)
assert(not pcall(string.rep, "x", 1000000000))
assert(load(string.rep(" ", 32769)) == nil)
return "sandbox-pass"
