local w, h = term.getSize()
local expected_w, expected_h = ...
assert(w == expected_w and h == expected_h)
assert(term.isColor() and term.isColour())
assert(term.getTextColour() == 1 and term.getBackgroundColor() == 32768)
term.clear()
term.setCursorPos(1, 1)
term.blit("ABC", "012", "fed")
assert(term.getCursorPos() == 4)
term.setCursorPos(-1, 2)
term.write("WXYZ")
assert(term.getCursorPos() == 3)
term.setCursorPos(1, 1)
assert(not pcall(term.blit, "bad", "00", "fff"))
assert(not pcall(term.blit, "bad", "0z0", "fff"))
assert(term.getCursorPos() == 1)
assert(not pcall(term.setCursorPos, 0/0, 1))
assert(not pcall(term.setTextColor, 3))
assert(not pcall(term.setBackgroundColour, math.huge))
assert(not pcall(term.setPaletteColor, 1, 2, 0, 0))
assert(not pcall(term.setPaletteColor, 1, -1))
term.setPaletteColour(1, 0x123456)
local r, g, b = term.getPaletteColor(1)
assert(r == 0x12/255 and g == 0x34/255 and b == 0x56/255)
term.setPaletteColor(2, 0.5, 0.25, 0.125)
r, g, b = term.getPaletteColour(2)
assert(r == 0.5 and g == 0.25 and b == 0.125)
term.setCursorBlink(true)
assert(term.getCursorBlink())
term.setCursorPos(1000, 1000)
term.write("offscreen")
assert(term.getCursorPos() == 1009)
term.setCursorPos(1, 3)
term.write("row3")
term.scroll(1)
term.scroll(-1)
term.setTextColor(8)
term.setBackgroundColor(16)
term.setCursorPos(1, 4)
term.clearLine()
return "terminal-pass"
