#!/usr/bin/env python3
"""Deterministically quote the allowlisted guest sources for Factorio's require."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def render(root=ROOT):
    manifest = json.loads((root / 'vendor/manifest.json').read_text())
    lines = ['-- Generated by tools/guest_rom_source.py from the verified vendor allowlist.', 'return {']
    records = sorted((r for r in manifest['files'] if 'guest_path' in r), key=lambda r: r['guest_path'])
    for record in records:
        source = (root / record['path']).read_text()
        separator = '='
        while f']{separator}]' in source:
            separator += '='
        # A leading newline is stripped by Lua long strings; explicitly supply it.
        lines.append(f'[{json.dumps(record["guest_path"])}] = [{separator}[\n{source}]{separator}],')
    lines.append('}')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    print(render(), end='')
