#!/usr/bin/env python3
"""Generate the native ROM overlay without modifying pinned vendor or VM bytes."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
PATCHES = {
    '/rc/editors/basic.lua': 'resources/native/patches/basic-save.patch',
    '/rc/editors/advanced.lua': 'resources/native/patches/advanced-save.patch',
    '/rc/modules/main/rc/io.lua': 'resources/native/patches/io-handle.patch',
}


def sha(data):
    return hashlib.sha256(data).hexdigest()


def render(root=ROOT):
    vendor_bytes = (root / 'vendor/manifest.json').read_bytes()
    vendor = json.loads(vendor_bytes)
    records = sorted((r for r in vendor['files'] if 'guest_path' in r), key=lambda r: r['guest_path'])
    assert len({r['guest_path'] for r in records}) == len(records), 'Duplicate native ROM path'
    actual_patches = {str(p.relative_to(root)) for p in (root / 'resources/native/patches').rglob('*') if p.is_file()}
    assert actual_patches == set(PATCHES.values()), 'Unexpected native patch inventory'
    lines = ['-- Generated by tools/native_rom_source.py; provenance: resources/native/manifest.json.', 'return {']
    inventory = []
    for record in records:
        data = (root / record['path']).read_bytes()
        assert sha(data) == record['sha256'], 'Native baseline resource changed: ' + record['path']
        assert record['copyright'] and record['license'] and (root / record['license_path']).is_file()
        item = {key: record[key] for key in ('guest_path', 'path', 'project', 'revision', 'source', 'source_url',
                                             'source_sha256', 'copyright', 'license', 'license_path')}
        item['baseline_sha256'] = sha(data)
        if record['guest_path'] in PATCHES:
            patch_path = PATCHES[record['guest_path']]
            patch = (root / patch_path).read_bytes()
            target = record['path'].replace('vendor/recrafted/', 'native/', 1)
            header = '--- ' + record['path'] + '\n+++ ' + target + '\n'
            assert patch.startswith(header.encode()) and b'\n--- ' not in patch, 'Invalid native patch baseline'
            with tempfile.TemporaryDirectory(dir=os.environ.get('TMPDIR')) as directory:
                original = Path(directory) / 'original.lua'
                original.write_bytes(data)
                result = subprocess.run(['patch', '--silent', '--fuzz=0', '--output=-', str(original)],
                                        input=patch, capture_output=True, check=True)
                assert not result.stderr and not result.stdout.startswith(b'patching file'), 'Unexpected patch output'
                data = result.stdout
            item['patch'] = patch_path
            item['patch_sha256'] = sha(patch)
        item['sha256'] = sha(data)
        inventory.append(item)
        source = data.decode('utf-8')
        separator = '='
        while f']{separator}]' in source:
            separator += '='
        lines.append(f'[{json.dumps(record["guest_path"])}] = [{separator}[\n{source}]{separator}],')
    lines.append('}')
    rom = '\n'.join(lines) + '\n'
    manifest = {'format': 1, 'backend': 'native', 'baseline_manifest': 'vendor/manifest.json',
                'baseline_manifest_sha256': sha(vendor_bytes), 'projects': vendor['projects'],
                'generated_path': 'scripts/native/rom.lua', 'generated_sha256': sha(rom.encode()), 'files': inventory}
    return rom, json.dumps(manifest, indent=2) + '\n'


def verify(root=ROOT):
    rom, manifest = render(root)
    assert (root / 'scripts/native/rom.lua').read_text() == rom, 'Generated native ROM is stale'
    assert (root / 'resources/native/manifest.json').read_text() == manifest, 'Native provenance manifest is stale'
    parsed = json.loads(manifest)
    return {'native_guest_files': len(parsed['files']), 'native_patches': len(PATCHES)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    if not args.check:
        rom, manifest = render()
        (ROOT / 'scripts/native/rom.lua').write_text(rom)
        (ROOT / 'resources/native/manifest.json').write_text(manifest)
    print(json.dumps(verify(), indent=2))


if __name__ == '__main__':
    main()
